name: Create Documentation
on: 
  push:
    tags:
      - '*'
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  create-documentation:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Build Documentation
        run: source Scripts/CreateDocumentation.sh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'Docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
