name: 'Test'
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - 'master'
jobs:
  run-tests:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Bootstrap Project
        uses: ./.github/actions/bootstrap-project
        with:
          example-constants: ${{ secrets.EXAMPLE_PROJECT_CONSTANTS }}
      - name: Run Tests
        run: bundle exec fastlane tests && bundle exec fastlane example_tests
